// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Verifies credentials and returns a 24-hour session token. Revokes any existing session for the user.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Authenticate with email and password",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin.loginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/admin.loginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/admin.swaggerErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/admin.swaggerErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/admin.swaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/providers": {
            "get": {
                "description": "Returns which login methods are enabled.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "List available authentication providers",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "Creates a customer account with a personal org, prepaid wallet, and first API key.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Public customer signup",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/admin.registerResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/admin.swaggerErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/admin.swaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/keys": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates a new API key. Members may only create user keys for themselves. The plaintext key is returned exactly once.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "keys"
                ],
                "summary": "Create an API key",
                "parameters": [
                    {
                        "description": "API key parameters",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin.createAPIKeyRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/admin.createAPIKeyResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/admin.swaggerErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/admin.swaggerErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/admin.swaggerErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/admin.swaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/keys/{key_id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns a single API key scoped by role.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "keys"
                ],
                "summary": "Get an API key",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API key ID",
                        "name": "key_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/admin.apiKeyResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/admin.swaggerErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/admin.swaggerErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/admin.swaggerErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/admin.swaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the profile of the user associated with the current session key.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Get authenticated user profile",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/admin.meResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/admin.swaggerErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/admin.swaggerErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/admin.swaggerErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/admin.swaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/me/available-models": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns models accessible to the caller's org, team, and key scope.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "List models available to the authenticated key",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/admin.availableModelsResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/admin.swaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/me/password": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Verifies the current password and sets a new one. Revokes all other active sessions. Requires a user-scoped session key.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Change own password",
                "parameters": [
                    {
                        "description": "Password change request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin.changeOwnPasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/admin.swaggerErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/admin.swaggerErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/admin.swaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/models": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns a cursor-paginated list of models. Requires system admin.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "models"
                ],
                "summary": "List models",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page size (default 20, max 100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Pagination cursor (UUIDv7 of the last seen model)",
                        "name": "cursor",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Include inactive models",
                        "name": "include_inactive",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/admin.paginatedModelsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/admin.swaggerErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/admin.swaggerErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/admin.swaggerErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/admin.swaggerErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Persists a new model and adds it to the live registry. The API key is encrypted at rest. Requires system admin.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "models"
                ],
                "summary": "Create a model",
                "parameters": [
                    {
                        "description": "Model parameters",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin.createModelRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/admin.modelResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/admin.swaggerErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/admin.swaggerErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/admin.swaggerErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/admin.swaggerErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/admin.swaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/models/health": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the latest health check results for all registered models. Requires member role or above.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "models"
                ],
                "summary": "Get upstream model health",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/admin.swaggerErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/admin.swaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/models/test-connection": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Probes the provider's /models endpoint to verify URL and API key without persisting any data. Requires system admin.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "models"
                ],
                "summary": "Test upstream provider connectivity",
                "parameters": [
                    {
                        "description": "Connection parameters",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin.testConnectionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/admin.testConnectionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/admin.swaggerErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/admin.swaggerErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/admin.swaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/models/{model_id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns a single model by ID. Requires system admin.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "models"
                ],
                "summary": "Get a model",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Model ID",
                        "name": "model_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/admin.modelResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/admin.swaggerErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/admin.swaggerErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/admin.swaggerErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/admin.swaggerErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Soft-deletes the model and removes it from the live registry. Requires system admin.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "models"
                ],
                "summary": "Delete a model",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Model ID",
                        "name": "model_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/admin.swaggerErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/admin.swaggerErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/admin.swaggerErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/admin.swaggerErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Updates model fields and refreshes the live registry. Requires system admin.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "models"
                ],
                "summary": "Update a model",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Model ID",
                        "name": "model_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Fields to update",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin.updateModelRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/admin.modelResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/admin.swaggerErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/admin.swaggerErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/admin.swaggerErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/admin.swaggerErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/admin.swaggerErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/admin.swaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/models/{model_id}/activate": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Marks the model as active and adds it to the live registry so proxy requests can use it immediately. Requires system admin.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "models"
                ],
                "summary": "Activate a model",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Model ID",
                        "name": "model_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/admin.modelResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/admin.swaggerErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/admin.swaggerErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/admin.swaggerErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/admin.swaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/models/{model_id}/deactivate": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Marks the model as inactive and removes it from the live registry. In-flight requests are not affected. Requires system admin.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "models"
                ],
                "summary": "Deactivate a model",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Model ID",
                        "name": "model_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/admin.modelResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/admin.swaggerErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/admin.swaggerErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/admin.swaggerErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/admin.swaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/models/{model_id}/deployments": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns all non-deleted deployments for the specified model, ordered by priority. Requires system admin.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "deployments"
                ],
                "summary": "List deployments",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Model ID",
                        "name": "model_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/admin.deploymentResponse"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/admin.swaggerErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/admin.swaggerErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/admin.swaggerErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/admin.swaggerErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates a new upstream deployment for the specified model. The API key is encrypted at rest. Requires system admin.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "deployments"
                ],
                "summary": "Create a deployment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Model ID",
                        "name": "model_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Deployment parameters",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin.createDeploymentRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/admin.deploymentResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/admin.swaggerErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/admin.swaggerErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/admin.swaggerErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/admin.swaggerErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/admin.swaggerErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/admin.swaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/models/{model_id}/deployments/{deployment_id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Soft-deletes a deployment and publishes a registry reload. Requires system admin.",
                "tags": [
                    "deployments"
                ],
                "summary": "Delete a deployment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Model ID",
                        "name": "modelId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Deployment ID",
                        "name": "deployment_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/admin.swaggerErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/admin.swaggerErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/admin.swaggerErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/admin.swaggerErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Partially updates a deployment and publishes a registry reload. Requires system admin.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "deployments"
                ],
                "summary": "Update a deployment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Model ID",
                        "name": "modelId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Deployment ID",
                        "name": "deployment_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Fields to update",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin.updateDeploymentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/admin.deploymentResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/admin.swaggerErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/admin.swaggerErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/admin.swaggerErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/admin.swaggerErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/admin.swaggerErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/admin.swaggerErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "admin.apiKeyResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "created_by": {
                    "type": "string"
                },
                "daily_token_limit": {
                    "type": "integer"
                },
                "expires_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "key_hint": {
                    "type": "string"
                },
                "key_type": {
                    "type": "string"
                },
                "last_used_at": {
                    "type": "string"
                },
                "monthly_token_limit": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "requests_per_day": {
                    "type": "integer"
                },
                "requests_per_minute": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "admin.availableModel": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "admin.availableModelsResponse": {
            "type": "object",
            "properties": {
                "models": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/admin.availableModel"
                    }
                }
            }
        },
        "admin.changeOwnPasswordRequest": {
            "type": "object",
            "properties": {
                "current_password": {
                    "type": "string"
                },
                "new_password": {
                    "type": "string"
                }
            }
        },
        "admin.createAPIKeyRequest": {
            "type": "object",
            "properties": {
                "daily_token_limit": {
                    "type": "integer"
                },
                "expires_at": {
                    "type": "string"
                },
                "key_type": {
                    "type": "string"
                },
                "monthly_token_limit": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "requests_per_day": {
                    "type": "integer"
                },
                "requests_per_minute": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "admin.createAPIKeyResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "created_by": {
                    "type": "string"
                },
                "daily_token_limit": {
                    "type": "integer"
                },
                "expires_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "key": {
                    "type": "string"
                },
                "key_hint": {
                    "type": "string"
                },
                "key_type": {
                    "type": "string"
                },
                "monthly_token_limit": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "requests_per_day": {
                    "type": "integer"
                },
                "requests_per_minute": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "admin.createDeploymentRequest": {
            "type": "object",
            "properties": {
                "api_key": {
                    "type": "string"
                },
                "azure_api_version": {
                    "type": "string"
                },
                "azure_deployment": {
                    "type": "string"
                },
                "base_url": {
                    "type": "string"
                },
                "cost_cache_write_per_1m": {
                    "type": "number"
                },
                "cost_cached_input_per_1m": {
                    "type": "number"
                },
                "cost_input_per_1m": {
                    "description": "Cost prices in USD per 1M tokens. Nil = fall back to model-level pricing.",
                    "type": "number"
                },
                "cost_output_per_1m": {
                    "type": "number"
                },
                "daily_request_limit": {
                    "type": "integer"
                },
                "gcp_location": {
                    "description": "GCPLocation is the Google Cloud region (e.g. \"us-central1\"). Required when provider is \"vertex\".",
                    "type": "string"
                },
                "gcp_project": {
                    "description": "GCPProject is the Google Cloud project ID. Required when provider is \"vertex\".",
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "pii_filter": {
                    "description": "PIIFilter explicitly enables or disables PII anonymization for requests\nrouted to this deployment. Omit to inherit from the model or network default.",
                    "type": "boolean"
                },
                "priority": {
                    "type": "integer"
                },
                "provider": {
                    "type": "string"
                },
                "provider_id": {
                    "description": "ProviderID links this route to a provider (partner/source).",
                    "type": "string"
                },
                "rpm_limit": {
                    "type": "integer"
                },
                "tpm_limit": {
                    "type": "integer"
                },
                "upstream_model": {
                    "description": "UpstreamModel is the model name sent upstream. Empty = use the model's\ncanonical name. Non-empty enables cross-model routes.",
                    "type": "string"
                },
                "weight": {
                    "type": "integer"
                }
            }
        },
        "admin.createModelRequest": {
            "type": "object",
            "properties": {
                "aliases": {
                    "description": "Aliases are optional short names that resolve to this model in proxy requests.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "api_key": {
                    "type": "string"
                },
                "azure_api_version": {
                    "type": "string"
                },
                "azure_deployment": {
                    "type": "string"
                },
                "base_url": {
                    "type": "string"
                },
                "bill_min_per_request": {
                    "type": "boolean"
                },
                "bill_per_request": {
                    "type": "boolean"
                },
                "bill_per_token": {
                    "type": "boolean"
                },
                "fallback_model_name": {
                    "description": "FallbackModelName is the name of the model to try if all deployments of\nthis model are unavailable. Requires an Enterprise license with the\nfallback_chains feature. Leave empty to disable fallback.",
                    "type": "string"
                },
                "gcp_location": {
                    "description": "GCPLocation is the Google Cloud region (e.g. \"us-central1\"). Required when provider is \"vertex\".",
                    "type": "string"
                },
                "gcp_project": {
                    "description": "GCPProject is the Google Cloud project ID. Required when provider is \"vertex\".",
                    "type": "string"
                },
                "input_price_per_1m": {
                    "type": "number"
                },
                "is_public": {
                    "description": "IsPublic marks the model as visible on the public storefront price list.",
                    "type": "boolean"
                },
                "logo": {
                    "description": "Logo is the customer-facing logo URL or asset path.",
                    "type": "string"
                },
                "max_context_tokens": {
                    "type": "integer"
                },
                "max_retries": {
                    "description": "MaxRetries is the maximum number of deployments to attempt before returning\nan error. 0 means try all available deployments.",
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "output_price_per_1m": {
                    "type": "number"
                },
                "pii_filter": {
                    "description": "PIIFilter explicitly enables or disables PII anonymization for requests\nrouted to this model. When omitted the network-level default is used.\nPass true to force anonymization on, false to force it off.",
                    "type": "boolean"
                },
                "provider": {
                    "type": "string"
                },
                "rpm_limit": {
                    "type": "integer"
                },
                "sell_cached_input_per_1m": {
                    "type": "number"
                },
                "sell_input_per_1m": {
                    "description": "SellInputPer1M / SellOutputPer1M / SellCachedInputPer1M are the\ncustomer-facing prices in USD per 1M tokens. Omit to leave the model\nunbilled (requests do not debit wallets).",
                    "type": "number"
                },
                "sell_min_per_request": {
                    "type": "number"
                },
                "sell_output_per_1m": {
                    "type": "number"
                },
                "sell_per_request": {
                    "type": "number"
                },
                "strategy": {
                    "description": "Strategy is the load balancing strategy used when multiple deployments are\nconfigured. Valid values: \"round-robin\", \"weighted\", \"priority\". Omit or\npass an empty string for single-deployment (legacy) mode.",
                    "type": "string"
                },
                "timeout": {
                    "description": "Timeout is the per-model upstream timeout as a Go duration string (e.g. \"30s\",\n\"2m\"). When non-empty it overrides the global stream/response timeout for\nthis model. Omit or pass an empty string to use the global default.",
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "admin.deploymentResponse": {
            "type": "object",
            "properties": {
                "azure_api_version": {
                    "type": "string"
                },
                "azure_deployment": {
                    "type": "string"
                },
                "base_url": {
                    "type": "string"
                },
                "cost_cache_write_per_1m": {
                    "type": "number"
                },
                "cost_cached_input_per_1m": {
                    "type": "number"
                },
                "cost_input_per_1m": {
                    "type": "number"
                },
                "cost_output_per_1m": {
                    "type": "number"
                },
                "created_at": {
                    "type": "string"
                },
                "daily_request_limit": {
                    "type": "integer"
                },
                "gcp_location": {
                    "description": "GCPLocation is the Google Cloud region. Non-empty only for provider \"vertex\".",
                    "type": "string"
                },
                "gcp_project": {
                    "description": "GCPProject is the Google Cloud project ID. Non-empty only for provider \"vertex\".",
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "model_id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "pii_filter": {
                    "description": "PIIFilter is the per-deployment PII anonymization override. Nil means\ninherit from the model-level or network-level default; true forces\nanonymization on; false forces it off.",
                    "type": "boolean"
                },
                "priority": {
                    "type": "integer"
                },
                "provider": {
                    "type": "string"
                },
                "provider_id": {
                    "type": "string"
                },
                "rpm_limit": {
                    "type": "integer"
                },
                "tpm_limit": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                },
                "upstream_model": {
                    "description": "UpstreamModel is the model name sent upstream; empty means the\ncanonical model name is used.",
                    "type": "string"
                },
                "weight": {
                    "type": "integer"
                }
            }
        },
        "admin.loginRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "admin.loginResponse": {
            "type": "object",
            "properties": {
                "expires_at": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/admin.meResponse"
                }
            }
        },
        "admin.meResponse": {
            "type": "object",
            "properties": {
                "display_name": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_system_admin": {
                    "type": "boolean"
                },
                "role": {
                    "type": "string"
                }
            }
        },
        "admin.modelResponse": {
            "type": "object",
            "properties": {
                "aliases": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "azure_api_version": {
                    "type": "string"
                },
                "azure_deployment": {
                    "type": "string"
                },
                "base_url": {
                    "type": "string"
                },
                "bill_min_per_request": {
                    "type": "boolean"
                },
                "bill_per_request": {
                    "type": "boolean"
                },
                "bill_per_token": {
                    "type": "boolean"
                },
                "created_at": {
                    "type": "string"
                },
                "deployments": {
                    "description": "Deployments contains the model's deployment entries when present.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/admin.deploymentResponse"
                    }
                },
                "fallback_model_name": {
                    "description": "FallbackModelName is the name of the fallback model, or empty when none\nis configured.",
                    "type": "string"
                },
                "gcp_location": {
                    "description": "GCPLocation is the Google Cloud region. Non-empty only for provider \"vertex\".",
                    "type": "string"
                },
                "gcp_project": {
                    "description": "GCPProject is the Google Cloud project ID. Non-empty only for provider \"vertex\".",
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "input_price_per_1m": {
                    "type": "number"
                },
                "is_active": {
                    "type": "boolean"
                },
                "is_public": {
                    "description": "IsPublic marks the model as visible on the public storefront price list.",
                    "type": "boolean"
                },
                "logo": {
                    "description": "Logo is the customer-facing logo URL or asset path.",
                    "type": "string"
                },
                "max_context_tokens": {
                    "type": "integer"
                },
                "max_retries": {
                    "description": "MaxRetries is the maximum number of deployments to attempt before\nreturning an error. 0 means try all available deployments.",
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "output_price_per_1m": {
                    "type": "number"
                },
                "pii_filter": {
                    "description": "PIIFilter is the per-model PII anonymization override. Nil means the\nnetwork-level default is used; true forces anonymization on; false off.",
                    "type": "boolean"
                },
                "provider": {
                    "type": "string"
                },
                "route_count": {
                    "description": "RouteCount is the number of enabled combo route steps (API products only).",
                    "type": "integer"
                },
                "routing_strategy": {
                    "type": "string"
                },
                "rpm_limit": {
                    "type": "integer"
                },
                "sell_cached_input_per_1m": {
                    "type": "number"
                },
                "sell_input_per_1m": {
                    "description": "Sell prices are the customer-facing prices per 1M tokens.",
                    "type": "number"
                },
                "sell_min_per_request": {
                    "type": "number"
                },
                "sell_output_per_1m": {
                    "type": "number"
                },
                "sell_per_request": {
                    "type": "number"
                },
                "source": {
                    "type": "string"
                },
                "sticky_round_robin_limit": {
                    "type": "integer"
                },
                "strategy": {
                    "description": "Strategy is the load balancing strategy used when multiple deployments\nare configured (e.g. \"round-robin\", \"weighted\", \"priority\"). An empty\nstring means single-deployment (legacy) mode.",
                    "type": "string"
                },
                "timeout": {
                    "description": "Timeout is the per-model upstream timeout (e.g. \"30s\", \"2m\").\nAn empty string means the global default is used.",
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "admin.paginatedModelsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/admin.modelResponse"
                    }
                },
                "has_more": {
                    "type": "boolean"
                },
                "next_cursor": {
                    "type": "string"
                }
            }
        },
        "admin.registerResponse": {
            "type": "object",
            "properties": {
                "api_key": {
                    "type": "string"
                },
                "expires_at": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/admin.meResponse"
                }
            }
        },
        "admin.swaggerErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/apierror.SwaggerDetail"
                }
            }
        },
        "admin.testConnectionRequest": {
            "type": "object",
            "properties": {
                "api_key": {
                    "type": "string"
                },
                "base_url": {
                    "type": "string"
                },
                "provider": {
                    "type": "string"
                }
            }
        },
        "admin.testConnectionResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "admin.updateDeploymentRequest": {
            "type": "object",
            "properties": {
                "api_key": {
                    "type": "string"
                },
                "azure_api_version": {
                    "type": "string"
                },
                "azure_deployment": {
                    "type": "string"
                },
                "base_url": {
                    "type": "string"
                },
                "cost_cache_write_per_1m": {
                    "type": "number"
                },
                "cost_cached_input_per_1m": {
                    "type": "number"
                },
                "cost_input_per_1m": {
                    "type": "number"
                },
                "cost_output_per_1m": {
                    "type": "number"
                },
                "daily_request_limit": {
                    "type": "integer"
                },
                "gcp_location": {
                    "description": "GCPLocation, when non-nil, replaces the stored Google Cloud region.",
                    "type": "string"
                },
                "gcp_project": {
                    "description": "GCPProject, when non-nil, replaces the stored Google Cloud project ID.",
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "pii_filter": {
                    "description": "PIIFilter, when non-nil, replaces the PII anonymization override for\nthis deployment. Pass true to force anonymization on, false to force it off.\nOmit the field entirely to leave the existing setting unchanged.",
                    "type": "boolean"
                },
                "priority": {
                    "type": "integer"
                },
                "provider": {
                    "type": "string"
                },
                "provider_id": {
                    "description": "ProviderID, when non-nil, replaces the linked provider. Pass \"\" to clear.",
                    "type": "string"
                },
                "rpm_limit": {
                    "type": "integer"
                },
                "tpm_limit": {
                    "type": "integer"
                },
                "upstream_model": {
                    "description": "UpstreamModel, when non-nil, replaces the upstream model name. Pass \"\"\nto revert to the canonical model name.",
                    "type": "string"
                },
                "weight": {
                    "type": "integer"
                }
            }
        },
        "admin.updateModelRequest": {
            "type": "object",
            "properties": {
                "aliases": {
                    "description": "Aliases, when non-nil, replaces the full set of aliases for the model.\nPass an empty slice to remove all aliases.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "api_key": {
                    "type": "string"
                },
                "azure_api_version": {
                    "type": "string"
                },
                "azure_deployment": {
                    "type": "string"
                },
                "base_url": {
                    "type": "string"
                },
                "bill_min_per_request": {
                    "type": "boolean"
                },
                "bill_per_request": {
                    "type": "boolean"
                },
                "bill_per_token": {
                    "type": "boolean"
                },
                "fallback_model_name": {
                    "description": "FallbackModelName, when non-nil, replaces the fallback model. Pass a\npointer to an empty string to clear the fallback. Requires Enterprise\nlicense with the fallback_chains feature when setting a non-empty value.",
                    "type": "string"
                },
                "gcp_location": {
                    "description": "GCPLocation, when non-nil, replaces the Google Cloud region.",
                    "type": "string"
                },
                "gcp_project": {
                    "description": "GCPProject, when non-nil, replaces the Google Cloud project ID.",
                    "type": "string"
                },
                "input_price_per_1m": {
                    "type": "number"
                },
                "is_public": {
                    "description": "IsPublic, when non-nil, replaces the storefront visibility flag.",
                    "type": "boolean"
                },
                "logo": {
                    "description": "Logo, when non-nil, replaces the customer-facing logo. Pass \"\" to clear.",
                    "type": "string"
                },
                "max_context_tokens": {
                    "type": "integer"
                },
                "max_retries": {
                    "description": "MaxRetries, when non-nil, replaces the maximum deployment retry count.",
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "output_price_per_1m": {
                    "type": "number"
                },
                "pii_filter": {
                    "description": "PIIFilter, when non-nil, replaces the PII anonymization override for this\nmodel. Pass true to force anonymization on, false to force it off, or\nomit the field entirely to leave the existing setting unchanged.\nSend the JSON key with a null value to clear the override and revert to\nthe network-level default (NULL in the DB).",
                    "type": "boolean"
                },
                "provider": {
                    "type": "string"
                },
                "routing_strategy": {
                    "type": "string"
                },
                "rpm_limit": {
                    "type": "integer"
                },
                "sell_cached_input_per_1m": {
                    "type": "number"
                },
                "sell_input_per_1m": {
                    "description": "Sell prices, when non-nil, replace the customer-facing prices.",
                    "type": "number"
                },
                "sell_min_per_request": {
                    "type": "number"
                },
                "sell_output_per_1m": {
                    "type": "number"
                },
                "sell_per_request": {
                    "type": "number"
                },
                "sticky_round_robin_limit": {
                    "type": "integer"
                },
                "strategy": {
                    "description": "Strategy, when non-nil, replaces the load balancing strategy. Pass a\npointer to an empty string to revert to single-deployment mode.",
                    "type": "string"
                },
                "timeout": {
                    "description": "Timeout, when non-nil, replaces the per-model timeout. Pass a pointer to\nan empty string to clear the timeout and revert to the global default.",
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "apierror.SwaggerDetail": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "not_found"
                },
                "message": {
                    "type": "string",
                    "example": "resource not found"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "API key (vl_uk_) or session key (vl_sk_)",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    },
    "tags": [
        {
            "description": "Authentication and user profile",
            "name": "auth"
        },
        {
            "description": "API key management",
            "name": "keys"
        },
        {
            "description": "User management",
            "name": "users"
        },
        {
            "description": "Model registry management",
            "name": "models"
        },
        {
            "description": "Model alias management",
            "name": "model-aliases"
        },
        {
            "description": "Dashboard statistics",
            "name": "dashboard"
        },
        {
            "description": "Usage analytics",
            "name": "usage"
        },
        {
            "description": "Prepaid wallet and top-ups",
            "name": "wallet"
        },
        {
            "description": "Upstream provider management",
            "name": "providers"
        },
        {
            "description": "Top-up review and marketplace admin",
            "name": "marketplace"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.2.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "VoidLLM API",
	Description:      "Prepaid LLM API marketplace with OpenAI-compatible proxy, wallet billing, and model catalog.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
